services:
  uptime-kuma:
    image: docker-registry.rahti.csc.fi/fiqci-workspace/uptime-kuma:v1.0
    volumes:
      - ./data:/app/data
    ports:
      # <Host Port>:<Container Port>
      - 3001:3001
    restart: unless-stopped
