version: '3.8'

services:
  uptime-kuma:
    container_name: uptime-kuma-dev
    image: docker-registry.rahti.csc.fi/fiqci-workspace/uptime-kuma:v1.0
    volumes:
      #- ./data:/app/data
      - ../server:/app/server
      - ../db:/app/db
    ports:
      - "3001:3001"  # <Host Port>:<Container Port>
      - "3307:3306"

