FROM louislam/uptime-kuma:base2
USER node
WORKDIR /app

ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=1
COPY --chown=node:node .npmrc .npmrc
COPY --chown=node:node package.json package.json
COPY --chown=node:node package-lock.json package-lock.json
RUN npm ci
COPY . .

RUN mkdir ./data
ENV UPTIME_KUMA_IS_CONTAINER=1
EXPOSE 3001
CMD ["node", "server/server.js"]
